apiVersion: batch/v1
kind: Job
metadata:
  name: sequential-job
spec:
  completions: 1 
  backoffLimit: 6
  activeDeadlineSeconds: 120 
  template:
    metadata:
      labels:
        app: crypto-emu
    spec:
      restartPolicy: OnFailure
      containers:
        - name: crypto-emulator
          image: diegob/crypto-emulator:1.6
