apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-eml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-eml
  template:
    metadata:
      labels:
        app: crypto-eml
    spec:
      containers:
      - name: crypto-eml
        image: diegob/crypto-emulator:1.61
