apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crypto-eml
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: crypto-eml
    spec:
      containers:
      - name: crypto-eml
        image: diegob/crypto-emulator:1.61
